=== MicheleMas/mensa-piovego-tecweb/piatti.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.mensapiovego.it" xmlns="http://www.mensapiovego.it" elementFormDefault="qualified">	
	<xsd:element name="piatti" type="Tpiatti" />
	<xsd:complexType name="Tpiatti">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="piatto" type="Tpiatto" />
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Tpiatto">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:string" />
			<xsd:element name="nomeITA" type="xsd:string" />
			<xsd:element name="nomeENG" type="xsd:string" />
			<xsd:element name="img" type="xsd:string" />
			<xsd:element name="altITA" type="xsd:string" />
			<xsd:element name="altENG" type="xsd:string" />
			<xsd:element name="descrizioneITA" type="xsd:string" />
			<xsd:element name="descrizioneENG" type="xsd:string" />
			<xsd:element name="commenti" type="Tcommenti" />
		</xsd:sequence>
		<xsd:attribute name="categoria" type="Tcategoria" use="required" />
	</xsd:complexType>
	<xsd:simpleType name="Tcategoria">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="primo"/>
			<xsd:enumeration value="secondo"/>
			<xsd:enumeration value="dessert"/>
    	</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="Tcommenti">
		<xsd:sequence minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="commento" type="Tcommento" />
		</xsd:sequence>	
	</xsd:complexType>
	<xsd:complexType name="Tcommento">
		<xsd:sequence>
			<xsd:element name="autore" type="xsd:string" />
			<xsd:element name="testo" type="xsd:string" />
			<xsd:element name="data" type="xsd:string" />
			<xsd:element name="email" type="xsd:string" />
		</xsd:sequence>
		<xsd:attribute name="lingua" type="Tlingua" use="required" />
	</xsd:complexType>
	<xsd:simpleType name="Tlingua">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ITA"/>
			<xsd:enumeration value="ENG"/>
    	</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== MicheleMas/mensa-piovego-tecweb/piatti.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="piatti.xsl" ?>
<!--<piatti xmlns="http://www.mensapiovego.it" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:schemaLocation="http://www.mensapiovego.it piatti.xsd"> -->
<piatti>
	<piatto id="1" categoria="primo">
		<nomeITA>Gnocchi al ragù</nomeITA>
		<nomeENG>Gnocchi with meat sauce</nomeENG>
		<img>gnocchi.png</img>
		<altITA>Gnocchi al sugo con abbondante ragù</altITA>
		<altENG>Gnocchi with lot of meat sauce</altENG>
		<descrizioneITA>Gli gnocchi sono uno dei piatti più famosi della tradizione italiana. Facili da preparare e gustosissimi se abbinati ad un sugo di carne come il ragù di carne proposto per il nostro menù. </descrizioneITA>
		<descrizioneENG>Gnocchi are one of the most famous dishes of the Italian tradition. Easy to prepare and tasty if combined with a gravy as the meat sauce for our menu. </descrizioneENG>
		<commenti>
			<commento lingua="ITA">
				<autore>cguarisc</autore>
				<testo>Gli gnocchi di oggi sembravano veramente di patate</testo>
				<data>2014/02/15</data>
				<email>c@guarisc.it</email>
			</commento>
			<commento lingua="ENG">
				<autore>cguarisc</autore>
				<testo>I liked it!</testo>
				<data>2014/02/16</data>
				<email>c@guarisc.it</email>
			</commento>
		</commenti>
	</piatto>
	
	<piatto id="2" categoria="primo">
		<nomeITA>Carbonara</nomeITA>
		<nomeENG>Carbonara</nomeENG>
		<img>carb.png</img>
		<altITA>Piatto di pasta alla carbonara</altITA>
		<altENG>A dish full with carbonara</altENG>
		<descrizioneITA>La pasta alla carbonara è un piatto caratteristico del Lazio e più in particolare di Roma preparato con ingredienti popolari e dal gusto intenso.</descrizioneITA>
		<descrizioneENG>Pasta alla carbonara is a dish typical of Lazio and Rome in particular prepared with ingredients and intense flavour.</descrizioneENG>
		<commenti>
			<commento lingua="ITA">
				<autore>cguarisc</autore>
				<testo>La carbonara di oggi era proprio buona. Ma va!!</testo>
				<data>2014/02/15</data>
				<email>c@guarisc.it</email>
			</commento>
		</commenti>
	</piatto>

	<piatto id="3" categoria="secondo">
		<nomeITA>Patate prezzemolate</nomeITA>
		<nomeENG>Parsley potatoes</nomeENG>
		<img>prezzemolate.png</img>
		<altITA>Patate prezzemolate con un po' di olio</altITA>
		<altENG>Parsley potateos with some oil</altENG>
		<descrizioneITA>Patate prezzemolate non so</descrizioneITA>
		<descrizioneENG>Parsley potatoes are unknown</descrizioneENG>
		<commenti>
			<commento lingua="ITA">
				<autore>cguarisc</autore>
				<testo>Ma cosa sono queste patate prezzemolate?</testo>
				<data>2014/02/22</data>
				<email>c@guarisc.it</email>
			</commento>
		</commenti>
	</piatto>

	<piatto id="4" categoria="secondo">
		<nomeITA>Pollo al limone</nomeITA>
		<nomeENG>Lemon Chicken</nomeENG>
		<img>pollolimone.png</img>
		<altITA>Un piatto con pollo al limone</altITA>
		<altENG>Dish of lemon chicken</altENG>
		<descrizioneITA>Il pollo al limone o pollo in salsa di limone è un piatto tipico della cucina cinese, creato e tramandato non dalla cucina tradizionale ma dalle comunità cinesi sparse nel mondo.</descrizioneITA>
		<descrizioneENG>The lemon chicken or chicken in lemon sauce is a typical dish of Chinese cuisine, created and passed down not from traditional cuisine but from Chinese communities around the world.</descrizioneENG>
		<commenti>
			<commento lingua="ITA">
				<autore>cguarisc</autore>
				<testo>Buono questo pollo al limone.. quasi quasi mi sto dissetando.</testo>
				<data>2014/02/25</data>
				<email>c@guarisc.it</email>
			</commento>
		</commenti>
	</piatto>

	<piatto id="5" categoria="dessert">
		<nomeITA>Crepes</nomeITA>
		<nomeENG>Crepes</nomeENG>
		<img>creepes.png</img>
		<altITA>Qualche piatto di crépes alla nutella</altITA>
		<altENG>Some dishes of crépes</altENG>
		<descrizioneITA>Le crêpes vengono farcite di ripieni vari, dolci o salati e arrotolate su se stesse per racchiuderli. L'impasto è a base di latte, uova, farina. La crêpe è generalmente considerata una pietanza tipica della cucina francese, tuttavia sono presenti preparazioni simili in vari paesi d'Europa.</descrizioneITA>
		<descrizioneENG>The crêpes are stuffed with various fillings, sweet or salted and rolled up on themselves to enclose them. The dough is made with milk, eggs, flour. The crêpe is generally considered a dish typical of French cuisine, but there are similar preparations in various European countries.</descrizioneENG>   
		<commenti>
			<commento lingua="ITA">
				<autore>mmassaro</autore>
				<testo>Che buone ne ho gia mangiate 10.</testo>
				<data>2014/02/25</data>
				<email>m@massaro.it</email>
			</commento>
		</commenti>
	</piatto>
</piatti>
